sudo: required

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

language: android

env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2

jdk:
  # the release build infrastructure uses OpenJDK from Debian
  #- openjdk7
  # many developers use the Oracle JDK
  # (disabled because Travis cannot reliably start the emulator with these)
  - oraclejdk8
  #- oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - build-tools-25.0.2
    - android-sdk-license-c81a61d9
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
    # only approve the non-Google licenses
    - android-sdk-license-c81a61d9
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

cache: false

script:
  # 'assemble' everything and run all checks that do not require a device/emulator
  - ./gradlew build -PdisablePreDex

after_failure:
  - find * -name lint-results.xml | xargs cat


